apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:i9cfravAAZ73AkYoNhINz6mAd0rHr1WPTqPzcvcx3L4y0jBx,iv:Id2pLWCXZdBHJlRR3BgywoA14CMP2SBKxtjzKt9qF5I=,tag:4oS6YGBpCeLEIeHyCuLLGg==,type:str]
    TUNNEL_SECRET: ENC[AES256_GCM,data:mkWodg3s2Bqkg2VyRVslywOQ9uMZOM0U1Q0yRMGesPKqzE4to9fRVROEQS+mLcM9EFJjOKiwUdAEIy4GOJnb5zhiOcgiU2phN7qAwJUtY8pqr1Ilczjn3VOnvl6yjYLScLLRLbbt/tIAE9XArMHEOd/bS0iNIRgCuH/2LlswF5X6Peo2YrP2RxxNsP1VxJX+P3xsApiv8ENXEnnHrdkkyVn4zfAyZPZq5tCJylQuUh3z0xg79Ipn0A==,iv:JNeqCdP7CFqcfVMDkWSuBX644qMBHFCKrczhJ9AV9ds=,tag:PnX7eUZh3V68Q2XU0X2iIw==,type:str]
    credentials.json: ENC[AES256_GCM,data:hePKnt3hwxCCSPsKxEld/Qe/lEh+uCBP3Rv1EpM1rweupnZCUhy1iVwGAZJ7m5TuPy4SZMS/6mw7VkTjNubVAv6dSuJT6JPxk7Q9sX0UQ/D9wYaZp3DGhp5uwojL2nvGGNM4go7HLvWO4Um8AjTYfCByQU8K6S3BWoUux/i0LOPtGVMRHGh5wkEB9LbSF/tGi1Jp7IvdumkdCIjfPO9s0vUQK0wHtUlA4qbsNqYYc7YmscYdHpSac+cQq++PtGc3xsC2WZ2USQ/LxfAO65cVcOPpB7SsCaBUllxuMRtQ25/XOch1ihr/UHZwHw5GG3PEtaXll+xITN8TBePhdM51mySgZ0qSMGiSCeLq3VZH9T3uZ3bEiEheIAj3Cvibf2/In7itkSqmsB4FSNu7yylQPVof8OABpFrW4fn3,iv:8vQzZqzaAXZkW0aapZxAEYegxzFoW25xURPjxrxevcY=,tag:aDt4dTF10kPYXAReAuu2qQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteVorMXgyaXR0VjMzM2oy
            c2hjY1NpUmhKRFlyRzNwSG8wc0Y1Q1Joc1VnClU3Zkx1eDU2Q3ZuVFF0MWdEaXVk
            elhMWXI2MmpWU3Z6TzRjbGxaa3kxbU0KLS0tIE4yeFJzdmtLRDBwaHIrMXJ0eldx
            Sm5DOEppcGhsNjlaREw5NmlqM21zaUkKHWpbMxEQH8Qc/lLJnP5eNgzNR1s6QSLm
            PFupuzUXxxde2skM+ACXvacimX7lPEupRdMK4DojRrFY1dzixYRrTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T23:00:07Z"
    mac: ENC[AES256_GCM,data:eas1xIdbvHTzTeLcrSshFcd9dne5XvJB8okY9zxomj85Qrihphh8JlKLNR07Oiju7Z+C9YdeapLQTEQHpzx1208O4a8lK7hCjhOZLZjbeROmEPYwuGy7Xri2NzeLrJEtDf1tKc414pHEyf5v7JAMEPjrSa05bRSrGWcc3c+m60M=,iv:V9WXVSCcbDQZ4Wb6fdG9Z1uPJjRRmCPWOKuUxdpYmqY=,tag:5WcS1ZcKrHdGytQsgB5eVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
