apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:9JN1Msq/8SXjJQLQDGkB70LEwXZlGvcExhFGHkByZbSEwOytE3/TEg==,iv:ysXtDVP+m5YLvOgr99njwpFFoOwBLdHRCVOuTnLo1Ak=,tag:3UXL0iARzDEVyr0DpFCW7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTmp2RnBadjlBNktaUC8z
            djlabHVudDQ0S0owZDhKaGZ5S1ZxZStiMzJrCmdmMklIK1N6RlRxTlM1V2EzTmsz
            Rmp6K01KMG9HbENYREtBc0w4M0Rua3cKLS0tIEhtUkExeHNsbVlVcWZDend5dHhF
            R090K3RiWU5aWlJYSDdNWHFHd3FQclkKUv2BrR+o9NihPgHpvld1m2Tr/rRzRWve
            yhfNsZzpSo1FUtFf1jNZFyG5b7bEf365Ug4Zaai0IrnY+iehQQGUcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T22:39:55Z"
    mac: ENC[AES256_GCM,data:JdVcveXusIHqPRfmRSnwGucQcvlXjfMgWvJ+YQ8RR75Uo/UY4lLsDN6WFdzqf3YtWCYdY0EjpdCx7O9sZEsQay2Cp4BDV65dVNub1OYFk82g3ELWOWKceclzooGTVi9sY/PNZ6uKk2ZhJuUiuEX1TDdi+u+WcqScMfXWGeXu2o4=,iv:MLXupMsLl0OyLNVMWjimZ6Gl8wglPr5kKsDzXvox3nk=,tag:zBCggFhyEgZ9iJr2kMVgVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
