---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: nas.przmo.com
  share: /Nebula-Apps-Data
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - "noatime"
#  - "hard"
...
