apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9VvK1bslBc1G,iv:nUAX8bjNVVFYStpzYBLhOcfYoXUDF+ssIAHeLvab/PQ=,tag:jorN5MRGLUlNLhzdjhbFaQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:dwggrZAeMfhA+GBOT88tHRVXa5e6xHdc6Q==,iv:DBEply7ZTevfZbmmI+65h7KM1D4f1X6f/QnJ+5FKn/0=,tag:1pvyNHDFS7ZUxhPToX45Cw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:uFnM8sTJ7MmK3498bkLNuVDD4nzedhtCSLQVEQLekAbP4zE+,iv:Zwm0hFjroNF48EJR1dctMFaBxND4zJW3VsfoenSEgec=,tag:JBIJ7itfc062UQxd6tqeYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEOERRYy9COUZQdWJEa3JM
            VnZTWkQ5TUdGSm9ZTk14b1FSRXo4OHU0OUdBCm9uYXhVMFlJampjekJKb0VMNzFS
            ZWQyazBrRytTcEI3NTJKSTVETXVub0kKLS0tIFhGWVpyc1lmVTVXSDY2anBoczZi
            QzdtRmxmL2Y1aHdpZjNxQytSOGlKS1kKsUrJUUhvVcwxdtDW8pjj0+229KH3dN+a
            ZRtEbhyIG6RxPKIA6GFBI4R1+yzCZFqNtNNgnqBOIk8Q7oZPAgB0PA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-12T00:15:00Z"
    mac: ENC[AES256_GCM,data:glGxdfwTBuUtSJOjM7i3VqjsfXWujQRz8zfxPpPSWmwgX+pjlwEdfvYYhlAwRC1ub7vMfeBW7g730S0dsO2jAoYuVdzJ4Wr707Qyr+gXEG4bLM89wBpuxg8kDf+C1HDvagkQMY/dxpHptPvugrTrumqavNPaxw1r+c9S0vCh0/I=,iv:GLYmE7Kzmq5JvE1cSwjTAVWIXOt8YXsQ9eOgwCftBL8=,tag:vWgElA97QwrRAjBhyF5ydw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
