apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:WF3pTAN5t0As,iv:Tp4+1zNgm0QLGj2D7ARNZgmehAUlIsDmOQcHecUHQHw=,tag:8EhXGZtMKqzqzzwv1Q/7Gw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:QyXSc4NTpO1VzkNjQaHnH0yCNIYBiXp4hg==,iv:SdBe6LgPEewc/WaKZ0gsGfW4ytJVoHaqC2C9FocZEj0=,tag:Tst0IiM5oqUHvIgfr7rnJg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RjdBL7BXn9n33TusJItoBYb9z19vlbG5+mFIqIvfhfTh0ar1,iv:Zi/yj76cwi7sURtHiD6477eHaMXil7/334fsGKfIoMA=,tag:QSuSengW0F6OhCmkDnww2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTTNVb29sTytEejBtMjJT
            MVBlZGp5Qkk0Qm5XdFBwZzJCUjF5ZDlpM2hFCmFxUzZBUEhzMFVUZU1Rd0JibEN6
            ZHBJMkU0S2JwV3BRMjNOT1luTXhRczQKLS0tIGxsYUh3RjNrQW1WNHVKQTNtRXNa
            MS9hQnVVTVpFK0o1LzlSbEZuQmJRVmMK61VHRyzqVemYSb+yZmL4y5i1z4kpIY65
            RfPgUVFnJeZyb91Fn9utFn+FKnJj0EzsMMngrfOEsebIU/eD4rluZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T23:00:07Z"
    mac: ENC[AES256_GCM,data:LyYgEG/TXrlwVLFe4xq39fuf9Y+BadvGi5qqKAxmhnbCju9wbBO6c1+shA2BqRVJnouz6ByLNBoiixfg91vaBgRVTUYq70VdydGLJuqdLdPcyy0fcGZTGpuBxPUyMoMdo8WnzhCEHV5zFwU8oiOcBlFPkMoBUkwiLciV700WgGs=,iv:QWLThkETeSEg1pb0PAqZ8r6fRIfFxRjeL3Xus++f+gU=,tag:nZAR1hBc1HkIkbSW4i6Jyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
