apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:312dYwCkAU4v1vgM1q9MdJI+bqzz2C6J42n23+ko24L60hy0bFpjSg==,iv:VB/hMwnTHm7tLPUKEUiautbGCc8mqtCJ6oqMq601ZhQ=,tag:jhKgO9W0/pOJnMmdop2E4Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMXM2SGgyV0JLQXJiTkZ6
            aGYwdFIvTkI5dW0zdjZGWU44eVN2OHhLeEJnCnhaZUVxbTU2WFZhWkNDY0xwa2N0
            YzNnZS9SN0JXY0FOK3llVXRIVFBFMjgKLS0tIGlYQmNrNC8rNkhPKzU0U2orSmNn
            T2I5OXg3N2JvMWM0YUhwNUNSUGtwaTAKBo/KB7wDZSRlPw13ZEITevAQHZcWYcj/
            X0xNv+nRJhu8gncOWtKcU6npRjz30g+GBO7O7H8qbLXb0T5N83mU6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T10:24:52Z"
    mac: ENC[AES256_GCM,data:WBk6KTXX0fQvj157tE+N1CwBFzvYahI8zeQ7A1FoZFX9BV9XcO2RiFFUpiNMI3kxJ5qkGDLBoUcmfWyWL3JT2YhyDrzMB5vFrmw8enn2hr9DBzIbZ7UQzm0QsUwxquCMtr6830uHB5cXu+umsIYI58h/uGURr8QcTEHpeMJUP2s=,iv:+yJNSfFg4iqV6/YH6RkbFB4p29Dn1anDw/nsIaFsUUM=,tag:IW+xA4S7lSdCAFmTIjM7yQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
