apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:RnI8uO/HKurQUBITcM3TZR6BYQlChSNd9Q4Hr8dE+sK/nN+fS3VOZA==,iv:VB12vOE/YYzBu7EjZ1Xdb338e/DvX4Ybw5RZ6358R9Q=,tag:SffrvYMYgu+7kUBa1wFneA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16yn3p0q63qwyame6pv8ywpjgchaqgvvztsklafwc08ar6sa38svqycjd30
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYNnV0c1NMbnFYbUFXT29j
            RkJlRGtRYmlRY2FDaXB3R3p5T0NzOXg5aXlnCi9aNWVWdTR0REVoS2xjcEM2bjZo
            RjEyZlhRRmxKbVlTMDRxTnFUOW0zbGcKLS0tIGtObzEydWYrRXJUeFlXeUZmODln
            djVUVXk4QXZXMU9jZVl1dFZxSzVJNTAKCDNffN6Nu0UoJsKPKa6X5hGp0rZtMhvP
            mYBpiCl8Yn9RXGKMD7QQwadofBVg4TFVgdI0DSp2xUW9e/M/fJDLBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T21:47:06Z"
    mac: ENC[AES256_GCM,data:eDJ4dHk24L/N+iuYtkYveoH9oNCwX4IA8qPrj7m2AY5AMWDQkDPF+FbNpgNf9cw6F/+jnCgdWa1d14q8DBQnN32UXTQszRxyrBR4FPqnNbhLbwpZuKLwy4hvkrg4o9ZFrPTLykYDBbpHxSedabgqyEWcNQSbyNmfFJZORys4sd0=,iv:1foX6UcJQNguUsx/zOOwMidS9TLGb6GyyPTK8vJBXZw=,tag:s7Khdziq+fcydwXQbhzbkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
